const HTTP_STATUS = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  ALREADY_REPORTED: 208,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INVALID_TOKEN: 498,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  SERVICE_UNAVAILABLE: 503,
};

const WB_ERRORS = {
  BAD_REQUEST: {
    status: HTTP_STATUS.BAD_REQUEST,
    code: "BAD_REQUEST",
    message: "BAD_REQUEST",
    name: "WBBadRequestError",
  },
  UNAUTHORIZED: {
    status: HTTP_STATUS.UNAUTHORIZED,
    code: "UNAUTHORIZED",
    message: "UNAUTHORIZED",
    name: "WBUnauthorizedError",
  },
  FORBIDDEN: {
    status: HTTP_STATUS.FORBIDDEN,
    code: "FORBIDDEN",
    message: "FORBIDDEN",
    name: "WBForbiddenError",
  },
  NOT_FOUND: {
    status: HTTP_STATUS.NOT_FOUND,
    code: "NOT_FOUND",
    message: "NOT_FOUND",
    name: "WBNotFoundError",
  },
  METHOD_NOT_ALLOWED: {
    status: HTTP_STATUS.METHOD_NOT_ALLOWED,
    code: "METHOD_NOT_ALLOWED",
    message: "METHOD_NOT_ALLOWED",
    name: "WBMethodNotAllowedError",
  },
  CONFLICT: {
    status: HTTP_STATUS.CONFLICT,
    code: "CONFLICT",
    message: "CONFLICT",
    name: "WBConflictError",
  },
  TOO_MANY_REQUESTS: {
    status: HTTP_STATUS.TOO_MANY_REQUESTS,
    code: "TOO_MANY_REQUESTS",
    message: "TOO_MANY_REQUESTS",
    name: "WBRateLimitError",
  },
  INVALID_TOKEN: {
    status: HTTP_STATUS.INVALID_TOKEN,
    code: "INVALID_TOKEN",
    message: "INVALID_TOKEN",
    name: "WBInvalidTokenError",
  },
  INTERNAL_SERVER_ERROR: {
    status: HTTP_STATUS.INTERNAL_SERVER_ERROR,
    code: "INTERNAL_SERVER_ERROR",
    message: "INTERNAL_SERVER_ERROR",
    name: "WBServerError",
  },
  NOT_IMPLEMENTED: {
    status: HTTP_STATUS.NOT_IMPLEMENTED,
    code: "NOT_IMPLEMENTED",
    message: "NOT_IMPLEMENTED",
    name: "WBNotImplementedError",
  },
  SERVICE_UNAVAILABLE: {
    status: HTTP_STATUS.SERVICE_UNAVAILABLE,
    code: "SERVICE_UNAVAILABLE",
    message: "SERVICE_UNAVAILABLE",
    name: "WBServiceUnavailableError",
  },
};

const WB_ERRORS_BY_STATUS = Object.fromEntries(
  Object.values(WB_ERRORS).map((error) => [error.status, error])
);

module.exports = {
  PRODUCTS_PER_PAGE: 100,
  PAGES_PER_CATALOG: 100,
  FEEDBACKS_PER_PAGE: 20,
  QUESTIONS_PER_PAGE: 30,
  HTTP_STATUS,
  WB_ERRORS,
  WB_ERRORS_BY_STATUS,
  URLS: {
    MAIN_MENU: "https://static-basket-01.wbbasket.ru/vol0/data/main-menu-ru-ru-v3.json",
    BRAND: {
      INFO_BY_NAME: "https://static-basket-01.wbbasket.ru/vol0/data/brands/{0}.json",
      INFO: "https://static-basket-01.wbbasket.ru/vol0/data/brands-by-id/{0}.json",
      IMAGE: "https://static-basket-01.wbbasket.ru/vol0/brand-flow-logos/by-id/{0}.webp",
      CATALOG: "https://catalog.wb.ru/brands/v4/catalog",
      CATALOG_INTERNAL: "https://www.wildberries.ru/__internal/catalog/brands/v4/catalog",
      ENRICH: "https://user-data-syncer.wb.ru/sellers/api/v1/enrich_brands",
      FILTERS: "https://catalog.wb.ru/brands/v8/filters",
      FILTERS_INTERNAL: "https://www.wildberries.ru/__internal/catalog/brands/v8/filters",
    },
    SUPPLIER: {
      INFO: "https://static-basket-01.wbbasket.ru/vol0/data/supplier-by-id/{0}.json",
      STOREFRONT: "https://static-basket-01.wbbasket.ru/vol0/constructor-api/shops/v3/{0}.json",
      CATALOG: "https://catalog.wb.ru/sellers/v4/catalog",
      CATALOG_INTERNAL: "https://www.wildberries.ru/__internal/catalog/sellers/v4/catalog",
      FILTERS: "https://catalog.wb.ru/sellers/v8/filters",
      FILTERS_INTERNAL: "https://www.wildberries.ru/__internal/catalog/sellers/v8/filters",
      SHIPMENT: "https://suppliers-shipment-2.wildberries.ru/api/v1/suppliers/{0}",
    },
    PROMOS: "https://www.wildberries.ru/webapi/settings/promo/get",
    PRODUCT: {
      CONTENT: "https://wbx-content-v2.wbstatic.net/ru/{0}.json",
      CARD: "https://basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/info/ru/card.json",
      SELLERS: "https://basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/info/sellers.json",
      PRICE_HISTORY: "https://basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/info/price-history.json",
      CERTIFICATE: "https://basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/info/certificate.json",
      EXTRADATA: "https://www.wildberries.ru/webapi/product/{0}/data",
      DETAILS: "https://card.wb.ru/cards/v4/detail",
      DETAILS_INTERNAL: "https://www.wildberries.ru/__internal/card/cards/v4/detail",
      FEEDBACKS: "https://feedbacks{0}.wb.ru/feedbacks/v2/{1}",
      QUESTIONS: "https://questions.wildberries.ru/api/v1/questions",
      DELIVERYDATA: "https://card.wb.ru/cards/list",
    },
    SEARCH: {
      SIMILAR_BY_NM: "https://in-similar.wildberries.ru/",
      EXACTMATCH: "https://search.wb.ru/exactmatch/ru/common/v18/search",
      EXACTMATCH_INTERNAL: "https://www.wildberries.ru/__internal/search/exactmatch/ru/common/v18/search",
      CATALOG: "https://wbxcatalog-ru.wildberries.ru/{}/catalog",
      HINT: "https://suggests.wb.ru/suggests/api/v7/hint",
      HINT_INTERNAL: "https://www.wildberries.ru/__internal/suggests/suggests/api/v7/hint",
      LIST: "https://card.wb.ru/cards/v4/list",
      LIST_INTERNAL: "https://www.wildberries.ru/__internal/card/cards/v4/list",
    },
    IMAGES: {
      TINY: "https://basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/images/tm/{4}.webp", // 900x1200
      BIG: "https://basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/images/big/{4}.webp", // 900x1200
      SMALL: "https://basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/images/c246x328/{4}.webp", // 900x1200
      MEDIUM: "https://basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/images/c516x688/{4}.webp", // 900x1200
      FEEDBACK_BASE: "https://feedbackphotos.wbstatic.net/",
    },
    // vol   = nm_id % 144
    // part  = floor(nm_id / 10000)
    // basket= switch(vol): <=11→"01", <=23→"02", ..., <=131→"11", <=143→"12", else "13"
    // Source: WB urlVideoProduct() in product_dist JS
    VIDEO: {
      // HLS playlist (m3u8). WB always requests "1440p". Use Utils.Card.videoURL(id, "hls")
      HLS: "https://videonme-basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/hls/{4}/index.m3u8",
      // MP4 preview. WB hardcodes "1.mp4" and "360p". Use Utils.Card.videoURL(id, "mp4")
      MP4: "https://videonme-basket-{0}.wbbasket.ru/vol{1}/part{2}/{3}/mp4/{4}/1.mp4",
    },
  },
  APPTYPES: {
    DESKTOP: 1,
    ANDROID: 32,
    IOS: 64,
  },
  WAREHOUSES: [
    {
      ID: 218987,
      name: "Алматы Атакент",
      address: "г.Алматы, ул. Тимирязева 42 павильон 7а",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 204939,
      name: "Астана",
      address: "Нур-Султан, Шоссе Алаш, 69/1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 324108,
      name: "Астана 2",
      address: "Караганда, 91/2",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 206236,
      name: "Белые Столбы",
      address: "Московская область, Домодедово, микрорайон Белые Столбы, владение Склады 104, с 4/1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50194132,
      name: "Белые Столбы: Горючее",
      address: "Московская область, Домодедово, микрорайон Белые Столбы, владение Склады 104, с 4/1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50172467,
      name: "Владивосток СГТ",
      address: "Центральный переулок, 3 С. Вольно-надеждинское, Приморский край",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301981,
      name: "Владимир Воршинское",
      address: "Российская Федерация, Владимирская область, муниципальный округ Собинский, территория Вайлдберриз, здание 1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301983,
      name: "Волгоград",
      address: "Дзержинский район, городской округ Волгоград",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 397484,
      name: "Волгоград: Питание",
      address: "Дзержинский район, городской округ Волгоград",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301808,
      name: "Воронеж",
      address: "Отрадненское сельское поселение, Новоусманский район, Воронежская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 365116,
      name: "Воронеж СГТ",
      address: "Воронежская область, м.р-н Новоусманский, с.п. Усманское 1-е, с Нечаевка, ул Виноградная, д. 97а",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 397485,
      name: "Воронеж: Питание",
      address: "Отрадненское сельское поселение, Новоусманский район, Воронежская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 317470,
      name: "Голицыно СГТ",
      address: "Минское шоссе, 43-й километр, вл1к3",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50173475,
      name: "Домодедово 2: Питание",
      address: "территория НК Парк Домодедово-2, деревня Кучино, городской округ Домодедово, Московская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50136788,
      name: "Домодедово-2",
      address: "территория НК Парк Домодедово-2, деревня Кучино, городской округ Домодедово, Московская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50181547,
      name: "Домодедово-2 СГТ",
      address: "территория НК Парк Домодедово-2, деревня Кучино, городской округ Домодедово, Московская область ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 397494,
      name: "Екатеринбург (Перспективная): Питание",
      address: "Екатеринбург, Перспективная улица строение 14",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 300571,
      name: "Екатеринбург - Перспективная 14",
      address: "Екатеринбург, Перспективная улица строение 14",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 325360,
      name: "Екатеринбург СГТ",
      address: "5-й Южный проезд ЕКАД, 237",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 117986,
      name: "Казань",
      address: "Казань Республика Татарстан, Зеленодольский район Новая тура 1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50182145,
      name: "Казань СГТ",
      address: "Российская Федерация,Республика Татарстан,Зеленодольский район, промышленный парк «Зеленодольск», 20",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 397486,
      name: "Казань: Питание",
      address: "Казань Республика Татарстан, Зеленодольский район Новая тура 1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50160964,
      name: "Климовск СГТ",
      address: "Московская область, Подольск, микрорайон Климовск, Бережковский проезд, 26 Координаты:",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 507,
      name: "Коледино",
      address: "г.Подольск, д. Коледино, ул. Троицкая 20",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50136510,
      name: "Коледино: Горючее",
      address: "Коледино, ул. Троицкая д. 20",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301809,
      name: "Котовск",
      address: "Тамбовская область, муниципальное образование город Котовск, район индустриальный парк Котовск, 3/8",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 397489,
      name: "Котовск: Питание",
      address: "Тамбовская область, муниципальное образование город Котовск, район индустриальный парк Котовск, 3/8",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 130744,
      name: "Краснодар (Тихорецкая)",
      address: "Краснодарский край, г. Краснодар, ул.Тихорецкая 40с1 ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 397488,
      name: "Краснодар (Тихорецкая): Питание",
      address: "Краснодарский край, г. Краснодар, ул.Тихорецкая 40с1 ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50151471,
      name: "Краснодар СГТ",
      address: "улица Почтовый Тракт, 999, Прикубанский внутригородской округ, Краснодар",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50162327,
      name: "Красный Бор СГТ",
      address: "Российская Федерация, Ленинградская область, Тосненский район, г.п. Красный Бор",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 305087,
      name: "Кузнецк СГТ",
      address: "г. Кузнецк ул. Победы 53",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 208277,
      name: "Невинномысск",
      address: "г. Невинномысск, ул. Тимирязева 16 ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50047765,
      name: "Нижний Тагил Восточное",
      address: "Свердловская область, г. Нижний Тагил ул. Восточное шоссе 22/1 ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50107386,
      name: "Нижний Тагил: Индустриальная СГТ",
      address: "Свердловская область, г. Нижний Тагил, ул. Индустриальная, д. 30/1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50157355,
      name: "Никольское СГТ",
      address: "Территориальное управление № 2 Администрации Дмитровского городского округа Дмитровский муниципальный округ, Московская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301805,
      name: "Новосемейкино",
      address: "Индустриальный парк Новосемейкино, городское поселение Новосемейкино, Красноярский район, Самарская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 397487,
      name: "Новосемейкино: Питание",
      address: "Индустриальный парк Новосемейкино, городское поселение Новосемейкино, Красноярский район, Самарская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50086256,
      name: "Новосибирск СГТ",
      address: "Российская Федерация, Новосибирская область, Новосибирский муниципальный район, сельское поселение Толмачевский сельсовет, платформа 3307 км, дом 30, корпус В1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 218210,
      name: "Обухово",
      address: "Московская область, Богородский городской округ, рабочий поселок Обухово, территория Атлант-Парк, дом 32, строение 5, Склад № 35",
      workTime: "24/7",
      isActive: true,
      isTransitActive: true,
    },
    {
      ID: 50158884,
      name: "Обухово СГТ",
      address: "территория Обухово-Парк, 7, посёлок городского типа Обухово, Богородский городской округ, Московская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50045809,
      name: "Пенза",
      address: "Новая ул., 100, посёлок Приовражное",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50138082,
      name: "Пенза СГТ",
      address: "Пензенская область, Бессоновский район, Бессоновский сельсовет",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50132971,
      name: "Пермь: Горючее",
      address: "территория ЛИС, 16/1, Пермский муниципальный округ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 117501,
      name: "Подольск",
      address: "Подольск Московская область, городской округ Подольск Поливановская улица 9",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 218623,
      name: "Подольск 3",
      address: "Московская область, Подольск, Поливановская улица, 9с3",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50181543,
      name: "Подольск 3 СГТ",
      address: "Российская Федерация, Московская область, город Подольск, Ул. Поливановская , 9к3",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301229,
      name: "Подольск 4",
      address: "Домодедовское шоссе 22",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 300169,
      name: "Радумля СГТ",
      address: "деревня Радумля, с4А",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301760,
      name: "Рязань (Тюшевское)",
      address: "Индустриальный промышленный парк Рязанский, Тюшевское сельское поселение, Рязанский район",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50154075,
      name: "Рязань (Тюшевское): Питание",
      address: "Индустриальный промышленный парк Рязанский, Тюшевское сельское поселение",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 300862,
      name: "СЦ Абакан 2",
      address: "г. Абакан, ул. Складская 11 стр",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 316879,
      name: "СЦ Актобе",
      address: "г. Актобе, район Астана, Промзона 679/12",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 214951,
      name: "СЦ Артем",
      address: "Приморский край, г. Артем, ул. Солнечная, д.46",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 302769,
      name: "СЦ Архангельск (ул Ленина)",
      address: "Архангельск, улица Ленина, 29",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 169872,
      name: "СЦ Астрахань",
      address: "Астрахань, ул. Рождественского, д.17",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 302988,
      name: "СЦ Астрахань (Солянка)",
      address: "Николаевское шоссе, 2В, пос. пригородный",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 215020,
      name: "СЦ Байсерке",
      address: "Алм. Обл с Байсерке Султана Бейбарса 1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 302737,
      name: "СЦ Барнаул",
      address: "Алтайский край, г. Барнаул, ул. Попова, д. 179Б",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 205228,
      name: "СЦ Белая Дача",
      address: "Яничкин проезд, 3",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 210557,
      name: "СЦ Белогорск",
      address: "Амурская область, г. Белогорск, ул. Кирова, д. 306",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 300363,
      name: "СЦ Брест",
      address: "Брестская область, Брест, Дубровская улица, 36В",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 158751,
      name: "СЦ Владикавказ",
      address: "РФ, РСО-Алания, Пригородный район, с. Михайловское, Ростовское шоссе, д.17",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 144649,
      name: "СЦ Владимир",
      address: "ул. Мещерская, 7а",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 210127,
      name: "СЦ Внуково",
      address: "Москва, поселение Марушкинское, квартал № 8",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 300219,
      name: "СЦ Вологда 2",
      address: "Вологда, Окружное шоссе 13 корпус 5",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 300461,
      name: "СЦ Гомель 2",
      address: "Гомель, Могилёвская улица 1/А",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 314137,
      name: "СЦ Гродно",
      address: "г. Гродно, ул. Суворова 298",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 302571,
      name: "СЦ Ереван",
      address: "Ереван Арташисян 106",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 218402,
      name: "СЦ Иваново",
      address: " Ивановская область, Ивановский район, Коляновское сельское поселение, деревня Игнатово, ул. Окружная, д. 16",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 218628,
      name: "СЦ Ижевск",
      address: "г. Ижевск, Воткинское ш., 302",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 131643,
      name: "СЦ Иркутск",
      address: "Иркутск, ул. Трактовая, 18/38а",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 117442,
      name: "СЦ Калуга",
      address: "2-й Академический проезд, 12",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 213849,
      name: "СЦ Кемерово",
      address: "Кемерово, ул. Тухачевского, 58",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 303219,
      name: "СЦ Киров",
      address: "г.Киров ул.Павла Корчагина 227А",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 205985,
      name: "СЦ Крыловская",
      address: "Краснодарский край, Крыловский район, ст. Крыловская, ул. Орджоникидзе, д. 161",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 302335,
      name: "СЦ Кузнецк",
      address: "Кузнецк, улица Победы, 53,",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 140302,
      name: "СЦ Курск",
      address: "Курск , ул. 50 лет Октября, зд. 179",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 160030,
      name: "СЦ Липецк",
      address: "Липецкая область, ул. Орловская, здание 25А.",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 209211,
      name: "СЦ Махачкала",
      address: "Россия, Республика Дагестан, Махачкала, 2-й проезд Казбекова, 16",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 361670,
      name: "СЦ Махачкала Сепараторная",
      address: "Сепараторная улица, 1, Махачкала, Республика Дагестан",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 211622,
      name: "СЦ Минск",
      address: "Беларусь, Минская обл., Минский р-н, Щомыслицкий с/с, 118/2, р-н Антонишки",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 205349,
      name: "СЦ Мурманск",
      address: "г. Мурманск, ул Промышленная 19",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 204952,
      name: "СЦ Набережные Челны",
      address: "Набережные Челны,  улица Моторная, здание 16/5 и здание16/6",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50144199,
      name: "СЦ Нижний Новгород Ларина",
      address: "Нижегородский район",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 211470,
      name: "СЦ Нижний Тагил",
      address: "Свердловская область, г. Нижний Тагил, ул. Индустриальная, д. 30",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 206708,
      name: "СЦ Новокузнецк",
      address: "Кемеровская область, г. Новокузнецк, Центральный район, просп. Курако, д. 51а, корпус 23.",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50181287,
      name: "СЦ Новосибирск 4",
      address: "Россия, Новосибирская обл., Новосибирский р-н, с. Толмачёво, ул. 3307-й км, 30кВ2",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 340443,
      name: "СЦ Новосибирск Докучаева ",
      address: "улица Докучаева, 1/2, Новосибирск",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 312807,
      name: "СЦ Обухово 2",
      address: "Московская область, Богородский городской округ, рабочий поселок Обухово, территория Атлант-Парк, дом 32, строение 5, Склад № 36",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 168458,
      name: "СЦ Омск",
      address: "г. Омск, ул. Раздольная, д 1к3",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 315199,
      name: "СЦ Оренбург Центральная",
      address: "Оренбург , Центральная улица , 29 ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 300987,
      name: "СЦ Смоленск 3",
      address: "Смоленск, Улица Лавочкина, 107",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 318294,
      name: "СЦ Софьино",
      address: "Логопарк Софьино, контрольно-пропускной пункт № 2 Московская область, Раменский городской округ, территория Логистический технопарк Софьино Корпус 8.",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 117866,
      name: "СЦ Тамбов",
      address: "ул. Волжская, 71Б",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 117456,
      name: "СЦ Тверь",
      address: "ул. Волоколамское шоссе, 51Б",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 204615,
      name: "СЦ Томск",
      address: "РФ, Томская область, г. Томск, ул.  Мичурина, д. 47, стр. 14.",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 205104,
      name: "СЦ Ульяновск",
      address: "Ульяновская область, г. Ульяновск, 14 проезд Инженерный, 9в",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 218644,
      name: "СЦ Хабаровск",
      address: "г.Хабаровск, ул. Зеленая д.3А",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 218225,
      name: "СЦ Челябинск 2",
      address: "г. Челябинск, Копейское шоссе, 88А",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 312259,
      name: "СЦ Шушары",
      address: "Шушары Московское шоссе 143",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50064725,
      name: "СЦ Шымкент Асар",
      address: "микрорайон Асар-2, 2113, Шымкент",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 338827,
      name: "СЦ Ярославль Громова",
      address: "Ярославская обл, г. Ярославль. ул. Громова, д. 9В",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 2737,
      name: "Санкт-Петербург (Уткина Заводь)",
      address: "Россия, Ленинградская обл, Всеволожский р-н, массив Карьер Мяглово, тер Снт Уткина Заводь 4 корп.4, ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50045612,
      name: "Санкт-Петербург СГТ",
      address: "территория промышленной зоны Восточная, 1, Лаголовское сельское поселение, Ломоносовский район, Ленинградская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301987,
      name: "Сарапул",
      address: "Г Сарапул, Ижевский тракт 22",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50098010,
      name: "Склад Великий Камень",
      address: "Пекинский проспект, 9, индустриальный парк Великий Камень, Смолевичский район, Минская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 332491,
      name: "Склад Владивосток",
      address: "территория опережающего социально-экономического развития Надеждинская, Надеждинский район, Приморский край",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50172704,
      name: "Склад Домодедово Шинный",
      address: "территория НК Парк Домодедово-2, деревня Кучино, городской округ Домодедово, Московская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50150595,
      name: "Склад Ереван",
      address: "Республика Армения, г. Ереван, Аджапняк, район Ахтанак 1-ая улица, 1-ый переулок, строение 61",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 387234,
      name: "Склад Истра",
      address: "Московская область, муниципальный округ Истра, деревня Давыдовское, индустриальный парк Кулон-Истра Дачная улица, с2",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50045246,
      name: "Склад Шушары",
      address: "Санкт-Петербург, Пушкинский район, поселок Шушары, Московское шоссе, 153к2",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50062129,
      name: "Софрино СГТ",
      address: "Московская область, городской округ Пушкинский, территория Автодорога М8 Холмогоры, километр 48-й, дом 2, строение 3",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50049050,
      name: "Софьино СГТ",
      address: "Московская область, Раменский городской округ, территория Логистический технопарк Софьино, 15 корпус 6.1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 217081,
      name: "Сц Брянск 2",
      address: "Брянская обл, г. Брянск, ул. Сталелитейная, дом 1. ",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 301806,
      name: "Тверь",
      address: "Эммаусское сельское поселение, Калининский муниципальный округ, Тверская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50158905,
      name: "Тверь СГТ",
      address: "Эммаусское сельское поселение, Калининский муниципальный округ, Тверская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 206348,
      name: "Тула",
      address: "Тульская область, муниципальное образование Алексин, 1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 321932,
      name: "Чашниково",
      address: "Территория Индустриальный парк Чашниково, городской округ Солнечногорск, Московская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50173498,
      name: "Чашниково СГТ",
      address: "Московская область, городской округ Солнечногорск, территория Индустриальный парк Чашниково, 5/1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50194130,
      name: "Чашниково: Горючее",
      address: "Территория Индустриальный парк Чашниково, городской округ Солнечногорск, Московская область",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50089332,
      name: "Челябинск СГТ",
      address: "Челябинск, Копейское Шоссе 88А",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 206968,
      name: "Чехов 1, Новоселки вл 11 стр 2",
      address: "Чеховский район, село Новоселки, Промышленная зона Новосёлки, вл11с2",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 210001,
      name: "Чехов 2, Новоселки вл 11 стр 7",
      address: "Московская обл. городской округ Чехов. Промышленная зона Новоселки, вл. 11 с. 7",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 397492,
      name: "Шушары: Питание",
      address: "Санкт-Петербург, Пушкинский район, поселок Шушары, Московское шоссе, 153к2",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50173471,
      name: "Щеглово (Холмогоры) СГТ",
      address: "Российская Федерация, Московская область, городской округ Пушкинский, территория Автодорога М8 Холмогоры, километр 48-й, дом2, строение 1",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 336442,
      name: "Щербинка: Горючее",
      address: "Московская область, Подольск, Вишнёвая улица, 11Б",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 120762,
      name: "Электросталь",
      address: "Московская область, Электросталь, посёлок Случайный, территория Массив 3, 5",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50148010,
      name: "Электросталь: Питание",
      address: "Московская область, Электросталь, посёлок Случайный, территория Массив 3, 5.",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 50045904,
      name: "Юрга",
      address: "Кемеровская область — Кузбасс",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
    {
      ID: 367641,
      name: "Ярославль СГТ",
      address: "Ярославская обл, г. Ярославль. ул. Громова, д. 9",
      workTime: "24/7",
      isActive: true,
      isTransitActive: false,
    },
  ],
  DESTINATIONS: {
    KRASNODAR: {
      ids: [-1059500, -108082, -269701, 12358062],
    },
    MOSCOW: {
      ids: [-1029256, -102269, -2162196, -1257786],
    },
    KAZAN: {
      ids: [-1075831, -79374, -367666, -2133462],
    },
    EKATERINBURG: {
      ids: [-1113276, -79379, -1104258, 123589409],
    },
    NOVOSIBIRSK: {
      ids: [-1221148, -140294, -1751445, -365403],
    },
    HABAROVSK: {
      ids: [-1221185, -151223, -1782064, -1785058],
    },
    GLOBAL: {
      ASTANA_KZ: {
        ids: [12358388, 12358412, -3479876, 85],
      },
      MINSK_BY: {
        ids: [12358386, 12358403, -70563, -8139704],
      },
      EREVAN_AM: {
        ids: [12358387, 12358400, -13404218, 36],
      },
      TASHKENT_UZ: {
        ids: [12358390, 12358442, -2448072, 491],
      },
      DUSHANBE_TJ: {
        ids: [-214626, -7328360, -11018181, 123589607],
      },
      ADDIS_ABABA_ET: {
        ids: [-192800, -1707699, -13422232, -11589495],
      },
      TBILISI_GE: {
        ids: [-28699, -1996871, -13438811, 123586302],
      },
    },
  },
  LOCALES: {
    RU: "ru",
  },
  CURRENCIES: {
    RUB: "rub",
  },
  SEX: {
    FEMALE: "female",
    MALE: "male",
    COMMON: "common",
  },
  USERAGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36",
};
